dragons:
    - dragonInfo:
        role: grinder
        scratch: e
        eliminate: s
    - dragonInfo:
        role: grinder
        scratch: e
        eliminate: s
    - dragonInfo:
        role: grinder
        scratch: e
        eliminate: s
captchaLogging: true
fastMode: true
numBattlesDefault: 50
battleLogic: SpamLogic
eliminateThreshold: 1